title = "DQN config"

lr=0.001
update_freq=10 
gamma=0.9 
epsilon=1
epsilon_decay=0.998
epsilon_min=0.01
replay_size=100 
target_update=50 
n_hidden=64 
replay_buffer_eps=100
episodes_without_training=500 
munchhausen=true 
assign_psng=false
min_pick_ups=1 
entropy_tau=0.03 
alpha=0.9

